# Generated by Django 5.2.5 on 2025-09-03 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='link_imagen',
        ),
    ]
