# Generated by Django 5.2.5 on 2025-09-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_link_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='link_imagen',
            field=models.URLField(blank=True),
        ),
    ]
